# Generated by Django 3.2.23 on 2024-02-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20240207_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='original_content',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
