# Generated by Django 3.2.23 on 2024-02-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_comment_original_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edited_coffee_experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
