# Generated by Django 3.2.23 on 2024-02-08 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_comment_edited_coffee_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='edited_coffee_experience',
        ),
    ]
